In [51]:
from PIL import Image
import numpy as np
import pyautogui
import time
import matplotlib.pyplot as m
CANVAS=[(465, 145), (497, 145), (529, 145), (561, 145), (593, 145), (625, 145), (657, 145), (689, 145), (721, 145), (753, 145), (465, 177), (497, 177), (529, 177), (561, 177), (593, 177), (625, 177), (657, 177), (689, 177), (721, 177), (753, 177), (465, 209), (497, 209), (529, 209), (561, 209), (593, 209), (625, 209), (657, 209), (689, 209), (721, 209), (753, 209), (465, 241), (497, 241), (529, 241), (561, 241), (593, 241), (625, 241), (657, 241), (689, 241), (721, 241), (753, 241), (465, 273), (497, 273), (529, 273), (561, 273), (593, 273), (625, 273), (657, 273), (689, 273), (721, 273), (753, 273), (465, 305), (497, 305), (529, 305), (561, 305), (593, 305), (625, 305), (657, 305), (689, 305), (721, 305), (753, 305), (465, 337), (497, 337), (529, 337), (561, 337), (593, 337), (625, 337), (657, 337), (689, 337), (721, 337), (753, 337), (465, 369), (497, 369), (529, 369), (561, 369), (593, 369), (625, 369), (657, 369), (689, 369), (721, 369), (753, 369), (465, 401), (497, 401), (529, 401), (561, 401), (593, 401), (625, 401), (657, 401), (689, 401), (721, 401), (753, 401), (465, 433), (497, 433), (529, 433), (561, 433), (593, 433), (625, 433), (657, 433), (689, 433), (721, 433), (753, 433), (465, 465), (497, 465), (529, 465), (561, 465), (593, 465), (625, 465), (657, 465), (689, 465), (721, 465), (753, 465), (465, 497), (497, 497), (529, 497), (561, 497), (593, 497), (625, 497), (657, 497), (689, 497), (721, 497), (753, 497), (465, 529), (497, 529), (529, 529), (561, 529), (593, 529), (625, 529), (657, 529), (689, 529), (721, 529), (753, 529), (465, 561), (497, 561), (529, 561), (561, 561), (593, 561), (625, 561), (657, 561), (689, 561), (721, 561), (753, 561), (465, 593), (497, 593), (529, 593), (561, 593), (593, 593), (625, 593), (657, 593), (689, 593), (721, 593), (753, 593), (465, 625), (497, 625), (529, 625), (561, 625), (593, 625), (625, 625), (657, 625), (689, 625), (721, 625), (753, 625), (465, 657), (497, 657), (529, 657), (561, 657), (593, 657), (625, 657), (657, 657), (689, 657), (721, 657), (753, 657), (465, 689), (497, 689), (529, 689), (561, 689), (593, 689), (625, 689), (657, 689), (689, 689), (721, 689), (753, 689), (465, 721), (497, 721), (529, 721), (561, 721), (593, 721), (625, 721), (657, 721), (689, 721), (721, 721), (753, 721), (465, 753), (497, 753), (529, 753), (561, 753), (593, 753), (625, 753), (657, 753), (689, 753), (721, 753), (753, 753)]
CANVAS2=[(10, 10), (42, 10), (74, 10), (106, 10), (138, 10), (170, 10), (202, 10), (234, 10), (266, 10), (298, 10), (10, 42), (42, 42), (74, 42), (106, 42), (138, 42), (170, 42), (202, 42), (234, 42), (266, 42), (298, 42), (10, 74), (42, 74), (74, 74), (106, 74), (138, 74), (170, 74), (202, 74), (234, 74), (266, 74), (298, 74), (10, 106), (42, 106), (74, 106), (106, 106), (138, 106), (170, 106), (202, 106), (234, 106), (266, 106), (298, 106), (10, 138), (42, 138), (74, 138), (106, 138), (138, 138), (170, 138), (202, 138), (234, 138), (266, 138), (298, 138), (10, 170), (42, 170), (74, 170), (106, 170), (138, 170), (170, 170), (202, 170), (234, 170), (266, 170), (298, 170), (10, 202), (42, 202), (74, 202), (106, 202), (138, 202), (170, 202), (202, 202), (234, 202), (266, 202), (298, 202), (10, 234), (42, 234), (74, 234), (106, 234), (138, 234), (170, 234), (202, 234), (234, 234), (266, 234), (298, 234), (10, 266), (42, 266), (74, 266), (106, 266), (138, 266), (170, 266), (202, 266), (234, 266), (266, 266), (298, 266), (10, 298), (42, 298), (74, 298), (106, 298), (138, 298), (170, 298), (202, 298), (234, 298), (266, 298), (298, 298), (10, 330), (42, 330), (74, 330), (106, 330), (138, 330), (170, 330), (202, 330), (234, 330), (266, 330), (298, 330), (10, 362), (42, 362), (74, 362), (106, 362), (138, 362), (170, 362), (202, 362), (234, 362), (266, 362), (298, 362), (10, 394), (42, 394), (74, 394), (106, 394), (138, 394), (170, 394), (202, 394), (234, 394), (266, 394), (298, 394), (10, 426), (42, 426), (74, 426), (106, 426), (138, 426), (170, 426), (202, 426), (234, 426), (266, 426), (298, 426), (10, 458), (42, 458), (74, 458), (106, 458), (138, 458), (170, 458), (202, 458), (234, 458), (266, 458), (298, 458), (10, 490), (42, 490), (74, 490), (106, 490), (138, 490), (170, 490), (202, 490), (234, 490), (266, 490), (298, 490), (10, 522), (42, 522), (74, 522), (106, 522), (138, 522), (170, 522), (202, 522), (234, 522), (266, 522), (298, 522), (10, 554), (42, 554), (74, 554), (106, 554), (138, 554), (170, 554), (202, 554), (234, 554), (266, 554), (298, 554), (10, 586), (42, 586), (74, 586), (106, 586), (138, 586), (170, 586), (202, 586), (234, 586), (266, 586), (298, 586), (10, 618), (42, 618), (74, 618), (106, 618), (138, 618), (170, 618), (202, 618), (234, 618), (266, 618), (298, 618)]
def pixel_rgb(img, x, y):
	r, g, b = img.getpixel((x, y))
	return (r, g, b)
	
def isEmpty(rgb):
    if rgb == (0,0,0):
        return 0
    return 1

def check_frame(item):
    board=[]
    pixel_y = 145
    for i in range(20):
        pixel_x = 465
        for j in range(10):
            board.append(isEmpty(pixel_rgb(item, pixel_x, pixel_y)))
            pixel_x += 32
        pixel_y += 32
    return board

def check(item):
     return list(map(lambda x: isEmpty(pixel_rgb(item, x[0], x[1])), CANVAS))

#,region=(448,13)

#pyautogui.screenshot('canvas.png')

img = pyautogui.screenshot().convert('RGB')

#m.imshow

In [52]:
def check_frame2(item):
    board=[]
    pixel_y = 10
    for i in range(20):
        pixel_x = 10
        for j in range(10):
            board.append(isEmpty(pixel_rgb(item, pixel_x, pixel_y)))
            pixel_x += 32
        pixel_y += 32
    return board

def check2(item):
     return list(map(lambda x: isEmpty(pixel_rgb(item, x[0], x[1])), CANVAS2))

In [53]:
x=time.time()
img = pyautogui.screenshot(region=(450,130,325,642)).convert('RGB')
print(np.reshape(check_frame2(img), (20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.030736923217773438


In [54]:
x=time.time()
img = pyautogui.screenshot(region=(450,130,325,642)).convert('RGB')
print(np.reshape(check2(img), (20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.03703427314758301


In [55]:
x=time.time()
img = pyautogui.screenshot(region=(450,130,325,642)).convert('RGB')
print(np.reshape([0 if pixel_rgb(img, i[0], i[1])==(0,0,0) else 1 for i in CANVAS2],(20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.03951716423034668


In [56]:
x=time.time()
img = pyautogui.screenshot().convert('RGB')
print(np.reshape(check_frame(img), (20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.03670239448547363


In [57]:
x=time.time()
img = pyautogui.screenshot().convert('RGB')
print(np.reshape(check(img), (20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.03913450241088867


In [58]:
x=time.time()
img = pyautogui.screenshot().convert('RGB')
print(np.reshape([0 if pixel_rgb(img, i[0], i[1])==(0,0,0) else 1 for i in CANVAS],(20,10)))
y=time.time()
print(y-x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 0 1 1]]
0.03226590156555176
